[potential]
potential_name = "TensorNet"

[potential.core_parameter]
number_of_per_atom_features = 128
number_of_interaction_layers = 2
number_of_radial_basis_functions = 32
maximum_interaction_radius = "10.0 angstrom"
minimum_interaction_radius = "0.0 angstrom"
maximum_atomic_number = 128
equivariance_invariance_group = "O(3)"

[potential.core_parameter.activation_function_parameter]
activation_function_name = "SiLU"

[potential.postprocessing_parameter]
[potential.postprocessing_parameter.per_atom_energy]
normalize = true
from_atom_to_molecule_reduction = true
keep_per_atom_property = true
[potential.postprocessing_parameter.general_postprocessing_operation]
calculate_molecular_self_energy = true


[dataset]
dataset_name = "SPICE2"
version_select = "nc_1000_v0"
num_workers = 4
pin_memory = true

[training]
number_of_epochs = 1000
remove_self_energies = true
batch_size = 32
lr = 0.5e-3
monitor_for_checkpoint = "val/per_molecule_energy/rmse"

[training.experiment_logger]
logger_name = "tensorboard"

[training.experiment_logger.tensorboard_configuration]
save_dir = "logs"

[training.lr_scheduler]
frequency = 1
mode = "min"
factor = 0.1
patience = 10
cooldown = 5
min_lr = 1e-8
threshold = 0.1
threshold_mode = "abs"
monitor = "val/per_molecule_energy/rmse"
interval = "epoch"

[training.loss_parameter]
loss_property = ['per_molecule_energy', 'per_atom_force'] # use

[training.loss_parameter.weight]
per_molecule_energy = 0.999 #NOTE: reciprocal units
per_atom_force = 0.001

[training.early_stopping]
verbose = true
monitor = "val/per_molecule_energy/rmse"
min_delta = 0.001
patience = 50

[training.splitting_strategy]
name = "random_record_splitting_strategy"
data_split = [0.8, 0.1, 0.1]
seed = 42

[runtime]
save_dir = "test_setup"
experiment_name = "{potential_name}_{dataset_name}"
local_cache_dir = "./cache"
accelerator = "gpu"
number_of_nodes = 1
devices = 1                                         #[0,1,2,3]
checkpoint_path = "None"
simulation_environment = "PyTorch"
log_every_n_steps = 1
